### ISSUE TITLE
Composer could not find the package at stable

### ISSUE THREAD

**Issue by arnaudbreton** [m1guelpf/php-sqreen-api#1]
Hi @m1guelpf and thanks for publishing this package.

While installing on my computer, with PHP 5.6.30 and composer 1.4.1 and running the composer require instruction: `composer require m1guelpf/sqreen-api`

I get back the following error:
```
  [InvalidArgumentException]
  Could not find package m1guelpf/sqreen-api at any version for your minimum-
  stability (stable). Check the package spelling or your minimum-stability
```

I had to run the following instruction to install it: `composer require m1guelpf/sqreen-api dev-master`. It seems the package has no stable version yet. 

Is it intended? Thanks for your feedback

**Comment by m1guelpf** [comment]
@arnaudbreton Fixed, thank you for reporting
